### ISSUE TITLE
"ValueError" when executing "MainCode" on "ARHCF_Mona_50nm" tutorial

### ISSUE THREAD

**Issue by MonaNis** [RonnyFoerster/NanoObjectDetection#1]
I get the following error output in my spyder console:

`t3_gapless = nd.get_trajectorie.close_gaps(t2_long)`
Traceback (most recent call last):

  File "<ipython-input-4-733b79d06cb9>", line 1, in <module>
    t3_gapless = nd.get_trajectorie.close_gaps(t2_long)

  File "C:\ProgramData\Anaconda3\NanoObjectDetection\get_trajectorie.py", line 315, in close_gaps
    t1_search_gap = t1_before.sort_values(by = ['particle', 'frame'])

  File "C:\Users\...\AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\core\frame.py", line 4711, in sort_values
    for x in by]

  File "C:\Users\...\AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\core\frame.py", line 4711, in <listcomp>
    for x in by]

  File "C:\Users\...\AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\core\generic.py", line 1701, in _get_label_or_level_values
    self._check_label_or_level_ambiguity(key, axis=axis)

  File "C:\Users\...\AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\core\generic.py", line 1655, in _check_label_or_level_ambiguity
    raise ValueError(msg)

**ValueError: 'frame' is both an index level and a column label, which is ambiguous.**

**Comment by MonaNis** [comment]
Ping @RonnyFoerster ...
Do you think, this is a pure pandas package issue? Or is the naming in our NanoObjectDetection's "get_trajectorie" function the problem?

**Comment by RonnyFoerster** [comment]
I think it is a problem in the code. I think I updated something which is now not compatible with this. Was running last week. I check it.

**Comment by RonnyFoerster** [comment]
Seit dem neusten update mag panda trackpy nicht mehr. Da kam schon immer ein wenig, dass das irgendwann so nicht mehr wird, aber es lief ja…. Also wir haben die Zeile frame zwei mal. Trackpy besteht drauf, Panda will es nicht. Yeah.

 

 

Ronny

 

 

 

 

Von: MonaNissen [mailto:notifications@github.com] 
Gesendet: Montag, 8. April 2019 14:59
An: RonnyFoerster/NanoObjectDetection
Cc: RonnyFoerster; Mention
Betreff: Re: [RonnyFoerster/NanoObjectDetection] "ValueError" when executing "MainCode" on "ARHCF_Mona_50nm" tutorial (#1)

 

Ping @RonnyFoerster <https://github.com/RonnyFoerster>  ...
Do you think, this is a pure pandas package issue? Or is the naming in our NanoObjectDetection's "get_trajectorie" function the problem?

**Comment by MonaNissen** [comment]
Oh nein, das klingt echt unglücklich. Heißt das jetzt, wir müssen eins von beiden eigenhändig umprogrammieren?! :/

Wobei, das Problem müssten dann eigentlich noch mehr Leute haben als nur wir, oder? Dann sollten wir es also mal auf der trackpy-Seite melden oder?



Von: RonnyFoerster [mailto:notifications@github.com]
Gesendet: Montag, 8. April 2019 16:23
An: RonnyFoerster/NanoObjectDetection
Cc: Nissen, Mona // Leibniz-IPHT; Author
Betreff: Re: [RonnyFoerster/NanoObjectDetection] "ValueError" when executing "MainCode" on "ARHCF_Mona_50nm" tutorial (#1)

Seit dem neusten update mag panda trackpy nicht mehr. Da kam schon immer ein wenig, dass das irgendwann so nicht mehr wird, aber es lief ja…. Also wir haben die Zeile frame zwei mal. Trackpy besteht drauf, Panda will es nicht. Yeah.





Ronny









Von: MonaNissen [mailto:notifications@github.com]
Gesendet: Montag, 8. April 2019 14:59
An: RonnyFoerster/NanoObjectDetection
Cc: RonnyFoerster; Mention
Betreff: Re: [RonnyFoerster/NanoObjectDetection] "ValueError" when executing "MainCode" on "ARHCF_Mona_50nm" tutorial (#1)



Ping @RonnyFoerster <https://github.com/RonnyFoerster> ...
Do you think, this is a pure pandas package issue? Or is the naming in our NanoObjectDetection's "get_trajectorie" function the problem?

**Comment by RonnyFoerster** [comment]
Panda(0.24.2) and Trackpy (0.4.1) are not compatible. The issue is solved by downgrading your panda back to the previous version 0.23.4.

The Tutorial.MonaARHCF is than working again.

I inserted a Pandas version test in the beginning. To stop in case version 0.24 or beyond is ussed.
