### ISSUE TITLE
Numpy-Array-Indexing for sizes_df_lin DataFrame - go back to integer indices?

### ISSUE THREAD

**Issue by MonaNis** [RonnyFoerster/NanoObjectDetection#14]
![sizes_df_lin_indexing](https://user-images.githubusercontent.com/49159556/88680725-18345500-d0f1-11ea-92c7-0b9959c62389.PNG)

**Comment by RonnyFoerster** [comment]
I cannot reproduce this. For me the index column is the particle id and an integer. Can you provide more details or a python script plus data on mars?
