### ISSUE TITLE
rolling_with_step function in CalcDiameter.py contains a dead link

### ISSUE THREAD

**Issue by MonaNis** [RonnyFoerster/NanoObjectDetection#30]

**Comment by MonaNis** [comment]
https://ga7g08.github.io/2015/01/30/Applying-python-functions-in-moving-windows/ is not working anymore. Is there some more information on that function elsewhere?

**Comment by MonaNis** [comment]
Furthermore, the `rolling_with_step` function seems to cut the last values. 
Example:
`nd.CalcDiameter.rolling_with_step(pd.Series([1,3,2,1,4,2,1,2]),2,2,nd.CalcDiameter.mean_func)`
`Out[]: `
`1    2.0`
`3    1.5`
`5    3.0`
`dtype: float64`
Where is the mean of the last two values gone?

_Originally posted by @MonaNis in https://github.com/RonnyFoerster/NanoObjectDetection/issues/31#issuecomment-720387772_

**Comment by RonnyFoerster** [comment]
Hi Mona, is that satisfying?

**Comment by MonaNis** [comment]
Looks good and passes simple tests, thank you 👍
