### ISSUE TITLE
AvgMsd function in CalcDiameter.py obsolete?

### ISSUE THREAD

**Issue by MonaNis** [RonnyFoerster/NanoObjectDetection#31]
It's not called in the CalcMSD function anymore - instead, AvgMsdRolling(..., DoRolling=False) is used.

Additionally, I have the following problem in understanding:
In both functions, the "independent" mean squared displacement values are calculated with
`nan_indi_means = rolling_with_step(nan_tm_sq[column], column, column, mean_func)`
Here, the rolling function appears.
Why is this necessary? There is no difference, whether I first calculate the mean of a and b and independently the mean of c and d... if I anyways take only the mean of these mean values later. I can directly calculate the mean of a, b, c and d, can't I? 
I'm confused here.

**Update:** 
I think I understand it better now. For the MSD calculation, this step is not necessary, only to get its error, right?

**Comment by MonaNis** [comment]
Furthermore, the `rolling_with_step` function seems to cut the last values. 
Example:
`nd.CalcDiameter.rolling_with_step(pd.Series([1,3,2,1,4,2,1,2]),2,2,nd.CalcDiameter.mean_func)`
`Out[]: `
`1    2.0`
`3    1.5`
`5    3.0`
`dtype: float64`
Where is the mean of the last two values gone?

**Comment by RonnyFoerster** [comment]
outcommented function AvgMsd
