### ISSUE TITLE
"Histogramm_time_Save": 1 - saves only an empty/white .png file

### ISSUE THREAD

**Issue by MonaNis** [RonnyFoerster/NanoObjectDetection#36]
The histogram over time is correctly displayed (in Spyder) but not correctly saved.

**Comment by RonnyFoerster** [comment]
so who takes care @MonaNis ?

**Comment by MonaNis** [comment]
It seems to be a problem of Spyder... saving works fine if plots are shown in separate windows but not if they are shown in the "plots" section of Spyder (which is some kind of "inline plotting" I assume).
Not a high priority issue anyways...

**Comment by RonnyFoerster** [comment]
@MonaNis have a look at the BugFix and close the issues if you are satisfied.

**Comment by MonaNis** [comment]
Looks good now, thank you :)
