### ISSUE TITLE
Plots that are not directly displayed are also not saved (i.e. not created)

### ISSUE THREAD

**Issue by MonaNis** [RonnyFoerster/NanoObjectDetection#9]
Example: 
If I choose the "Plot" parameters in my json-file as 
`"Histogramm_Show": 0,
"Histogramm_Save": 1`
no histogram file is created (and therefore cannot be found in the resp. folder).

**Comment by RonnyFoerster** [comment]
is that still existing mona?

**Comment by MonaNis** [comment]
If I use the same parameters as above, now the file is created - and also displayed directly. So we are actually still not there yet...

**Comment by RonnyFoerster** [comment]
because it is displayed although it shouldn't be?

**Comment by MonaNis** [comment]
Yes, exactly

**Comment by RonnyFoerster** [comment]
In order to save a plot, the plot needs to be created (and plotted) first. Thats why, if Histogramm_Save == 1, the plot will be shown no matter what the value of  Histogramm_Save is. We could try closing it afterwatds
